# This config should be placed in following path: /root/parity/config.toml

[parity]
# chain = "ropsten"

[ui]
disable = true

[rpc]
interface = "0.0.0.0"
#cors = %RPC_CORS%
apis = ["rpc"]

[ipc]
disable = true

[dapps]
disable = true

[footprint]
#pruning_history = 1201
cache_size = 8
pruning_memory = 33

#[ws]
#interface = "0.0.0.0"
#apis = ["rpc"]

[secretstore]
disable = true

[ipfs]
#disable = true